<?php
// This script generates a secure password hash.

$passwordToHash = 'Sumit@866800';

$hash = password_hash($passwordToHash, PASSWORD_DEFAULT);

echo "<h1>Your Personal Password Hash</h1>";
echo "<p>Password to hash: <b>" . htmlspecialchars($passwordToHash) . "</b></p>";
echo "<p>Below is the new, secure hash generated by your specific PHP environment. Copy this entire value for the next step.</p>";
echo '<textarea rows="3" cols="70" readonly onclick="this.select();">' . htmlspecialchars($hash) . '</textarea>';
echo "<p><i>(Clicking the text box will select the entire hash.)</i></p>";

?>